import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://zoo.gdansk.pl/en/homepage/');
  await page.getByRole('link', { name: 'en', exact: true }).click();
  await page.getByRole('button', { name: 'Zgadzam się' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.locator('#top-menu-box').getByRole('link', { name: 'Tickets' }).click();
  const page1 = await page1Promise;
  await page1.getByRole('img', { name: 'ZOO visit' }).click();
  await page1.goto('https://bilety.zoo.gda.pl/rezerwacja/nienumerowane.html?ter_id=4339&ter_idt=b92ff7fcf588ebcc1fda706326e23020');
  await page1.getByRole('spinbutton', { name: 'Normal ticket' }).click();
  await page1.getByRole('spinbutton', { name: 'Reduced ticket' }).click();
  await page1.getByRole('spinbutton', { name: 'Reduced ticket' }).fill('');
  await page1.getByRole('spinbutton', { name: 'Family ticket' }).click();
  await page1.getByRole('spinbutton', { name: 'Family ticket' }).fill('');
  await page1.getByRole('spinbutton', { name: 'Group ticket' }).click();
  await page1.getByRole('spinbutton', { name: 'Free ticket for children' }).click();
  await page1.getByRole('spinbutton', { name: 'Free ticket for children' }).fill('');
  await page1.getByRole('spinbutton', { name: 'Group ticket' }).click();
  await page1.getByRole('spinbutton', { name: 'Group ticket' }).fill('');
  await page1.getByRole('button', { name: 'Continue' }).click();
//   await page1.goto('https://bilety.zoo.gda.pl/koszyk/rezerwujacy.html');
//   await page1.getByText('en:Masz już konto? en:Zaloguj').click();
//   await page1.locator('#form_login_email').click();
//   await page1.locator('#form_login_email').fill('a@b.c');
//   await page1.getByRole('textbox', { name: 'Password' }).click();
//   await page1.getByRole('textbox', { name: 'Password' }).fill('dddddd');
//   await page1.getByRole('button', { name: 'Log in' }).click();
//   await page1.goto('https://bilety.zoo.gda.pl/');
//   await page1.getByText('en:Zamknij').click();
//   await page1.getByText('Select type and number of tickets').click();
//   await page1.getByRole('img', { name: 'ZOO visit' }).click();
//   await page1.goto('https://bilety.zoo.gda.pl/rezerwacja/nienumerowane.html?ter_id=4339&ter_idt=b92ff7fcf588ebcc1fda706326e23020');
//   await page1.getByRole('spinbutton', { name: 'Normal ticket' }).click();
//   await page1.getByRole('spinbutton', { name: 'Normal ticket' }).fill('');
  await page1.getByRole('button', { name: 'Continue' }).click();
  await page1.goto('https://bilety.zoo.gda.pl/koszyk/index.html');
});