import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://zoo.gdansk.pl/en/homepage/');
  await page.getByRole('button', { name: 'Zgadzam się' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.locator('#top-menu-box').getByRole('link', { name: 'Tickets' }).click();
  const page1 = await page1Promise;
  await page1.locator('#terminy div').filter({ hasText: 'ZOO visitDate of the visit01.' }).first().click();
  await page1.getByRole('row', { name: 'Reduced ticket Reduced' }).getByRole('button').nth(1).click();
  await page1.getByRole('button', { name: 'Continue' }).click();
  await page1.locator('#form_login_email').click();
  await page1.locator('#form_login_email').fill('a@b.c');
  await page1.locator('#form_login_email').press('Tab');
  await page1.getByRole('textbox', { name: 'Password' }).fill('dddddd');
  await page1.getByRole('button', { name: 'Log in' }).click();
  await page1.locator('#notice-modal').click();
  await page1.getByRole('button', { name: 'I buy and pay' }).click();
  await page1.getByRole('checkbox', { name: 'I declare that I have read' }).check();
  await page1.getByRole('button', { name: 'I buy and pay' }).click();
  await page1.getByRole('button', { name: 'Pay' }).click();
  const page2Promise = page.waitForEvent('popup');
  await page.locator('#top-menu-box').getByRole('link', { name: 'Tickets' }).click();
  const page2 = await page2Promise;
  await page2.getByRole('img', { name: 'ZOO visit' }).click();
  await page2.getByRole('row', { name: 'Family ticket Family tickets' }).getByRole('button').nth(1).click();
  await page2.getByRole('button', { name: 'Continue' }).click();
  await page2.getByRole('checkbox', { name: 'I declare that I have read' }).check();
  await page2.getByRole('button', { name: 'I buy and pay' }).click();
  await page2.getByRole('button', { name: 'Pay' }).click();
});